import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    "projects/overview",
    "projects/Baby-Tools-Shop/baby-tools-shop",
    "projects/Conduit-Container/conduit-container",
    "projects/Conduit-Deployment/conduit-deployment",
    "projects/Minecraft/minecraft",
    {
      type: "category",
      label: "OWASP Juice Shop",
      items: [
        "projects/OWASP-Juice-Shop/juice-shop",
        "projects/OWASP-Juice-Shop/sqli-attack-chain/README",
        "projects/OWASP-Juice-Shop/admin-takeover/README",
        "projects/OWASP-Juice-Shop/osint-chain/README",
        "projects/OWASP-Juice-Shop/captcha-bypass/README",
      ],
    },
    "projects/Truck-Signs-API/truck-signs-api",
    "projects/V-Server Setup/vserver-setup",
    "projects/Wordpress/wordpress",
  ],
};

export default sidebars;

// import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
// const sidebars: SidebarsConfig = {
// By default, Docusaurus generates a sidebar from the docs folder structure
// tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
// tutorialSidebar: [{type: 'autogenerated', dirName: 'projects'}],
// guidesSidebar: [{type: 'autogenerated', dirName: './knowlegde-base'}]

// But you can create a sidebar manually
/*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
// };

// export default sidebars;
